export const CommonErrorCodes = {
	FAILED_VALIDATION: 'FAILED_VALIDATION_EXCEPTION',
	CONFIG_INVALID: 'CONFIG_INVALID_EXCEPTION',
	CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND_EXCEPTION',
	UNKNOWN_EXCEPTION: 'UNKNOWN_EXCEPTION',
} as const

export const LinksErrorCodes = {
	SHARABLE_LINK_NOT_FOUND: 'SHARABLE_LINK_NOT_FOUND',
	SHARABLE_LINKS_RATE_LIMIT_EXCEEDED: 'SHARABLE_LINKS_RATE_LIMIT_EXCEEDED',
} as const
