export const CommonErrorCodes = {
	FAILED_VALIDATION: 'FAILED_VALIDATION_EXCEPTION',
	CONFIG_INVALID: 'CONFIG_INVALID_EXCEPTION',
	CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND_EXCEPTION',
	UNKNOWN_EXCEPTION: 'UNKNOWN_EXCEPTION',
} as const
