const MOODLE_EXCEPTION_CODE = {
	API_ERROR: 'MOODLE_API_ERROR',
	NON_JSON_API_RESPONSE_ERROR: 'MOODLE_NON_JSON_API_RESPONSE_ERROR',
	LOGIN_FAILED_ERROR: 'MOODLE_LOGIN_FAILED',
	INVALID_TOKEN_ERROR: 'MOODLE_INVALID_TOKEN',
	RECORD_NOT_FOUND_ERROR: 'MOODLE_RECORD_NOT_FOUND_ERROR',
} as const

type MoodleExceptionCode =
	(typeof MOODLE_EXCEPTION_CODE)[keyof typeof MOODLE_EXCEPTION_CODE]

export { MOODLE_EXCEPTION_CODE }
export type { MoodleExceptionCode }
